safe:        false
source:      .
destination: ./_site
plugins:     ./_plugins

excerpt_separator: "<!-- more -->"

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   /:year/:month/:day/:title

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
